#springfox.documentation.swagger.v2.path: /api-docs
spring:
  profiles.active: local-sandbox
  main.banner-mode: 'off'
server:
#  contextPath: /test
  compression:
    enabled: true
    mime-types: application/json
---

## Local sandbox configuration #################################################
spring:
  profiles: local-sandbox
  profiles.include: local-sandbox-endpoint,local-sandbox-h2 
---

## Local sandbox endpoint configuration #################################################
spring.profiles: local-sandbox-endpoint
qepp:
  encryptionKey: UmF2aSBTYW5rYXIgUmVkZHkgQ2hhbGxh
  initVector: UWFudGFzIFBheW1l
  connectTimeout: 3000
  readTimeout: 60000
  enableDevelopmentProxy: false
  devProxyHostName: test.proxy.com
  devProxyPort: 8080
  enableRestClientRequestResponseLogging: true
--- 
  
## Local sandbox database configuration
spring:
  profiles: local-sandbox-h2
  datasource:
    url: jdbc:h2:mem:qeppdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Mysql
    platform: h2
    jmx-enabled: true
  tomcat: 
    maxWait: 10000
    maxActive: 300
    testOnBorrow: true
    initialSize: 10
    minIdle: 30
    removeAbandoned: true
    removeAbandonedTimeout: 120
    validationQueryTimeout: 3
    testWhileIdle: true
    #validationQuery: '/* ping */ SELECT 1'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    #database-platform: org.hibernate.dialect.H2Dialect
    properties:
      enable_lazy_load_no_trans: true
      hibernate:
        format-sql: true
        show-sql: true
        type: trace 
        #globally-quoted-identifiers: true
flyway:
    enabled: false
logging.level.org.hibernate.internal.util.EntityPrinter: trace
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
logging.level.org.springframework.cache: trace
---

## Environments configuration
spring.profiles: dev,stage,production
qepp:
  encryptDecryptKey: ${encryptDecryptKey}
  initVector: ${initVector}
  connectTimeout: 3000
  readTimeout: 60000
---  